name: BedWars-Clan-Stats
version: ${project.version}
author: Simonsator
depends: [Clans]
main: de.simonsator.partyandfriends.clan.extensions.stats.bedwarsbukkitpvp.BWPlugin
description: Adds the stats of BedWars from BukkitPVP to clans